### PR TITLE
[REVIEW][FEATURE][GAWE-37] - Create component button

### PR DESCRIPTION
**Pull request by triandamai**
#### Description

> See documented sampe for usage.

#### Ticket Reference(s)

[GAWE-37](https://bluehabit.atlassian.net/browse/GAWE-37)

##### UI Changes

> 

##### Coverage

> Test coverage screenshot.

Screenshot 2023-08-10 at 11 59 39

Screenshot 2023-08-10 at 12 05 53

Screenshot 2023-08-10 at 11 59 52

Screenshot 2023-08-10 at 11 59 57

N/A

#### Note(s)

> Mention other user or extra note unrelated to the MR here.

[GAWE-37]: https://bluehabit.atlassian.net/browse/GAWE-37?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by marioprasetyo** [comment]
lgtm!

**Review by azkifairuz — COMMENTED** [review]
LGTM!

**Comment by triandamai** [comment]
Approve doong

**Comment by azkifairuz** [comment]
> Approve doong

Caranya gmn

**Review by azkifairuz — APPROVED** [review]
LGTM!

**Pull request merged**
